export const ADD_EVENT_REQUEST = "ADD_EVENT_REQUEST";
export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS";
export const ADD_EVENT_FAIL = "ADD_EVENT_FAIL";
export const DELETE_EVENT = "DELETE_EVENT";

export const LIST_EVENTS_REQUEST = "LIST_EVENTS_REQUEST";
export const LIST_EVENTS_SUCCESS = "LIST_EVENTS_SUCCESS";
export const LIST_EVENTS_FAIL = "LIST_EVENTS_FAIL";

export const LIST_EVENT_DETAILS_REQUEST = "LIST_EVENT_DETAILS_REQUEST";
export const LIST_EVENT_DETAILS_SUCCESS = "LIST_EVENT_DETAILS_SUCCESS";
export const LIST_EVENT_DETAILS_FAIL = "LIST_EVENT_DETAILS_FAIL";

export const ADD_INVITEE_REQUEST = "ADD_INVITEE_REQUEST";
export const ADD_INVITEE_SUCCESS = "ADD_INVITEE_SUCCESS";
export const ADD_INVITEE_FAIL = "ADD_INVITEE_FAIL";
export const DELETE_INVITEE = "DELETE_INVITEE";
